### PR TITLE
feat: release 0.5.0

### PR DESCRIPTION
**Pull request by joyyir**
Please answer these questions before submitting a pull request

- Why submit this pull request?
Release 0.5.0

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
Why do we need a release?

**Comment by joyyir** [comment]
> Why do we need a release?

A few months ago, there was a bug in version 0.4.0, so I worked on fixing it. However, since the release was not carried out for a long time, I decided to release it myself.

**Comment by monkeyDluffy6017** [comment]
It looks like that you missed the readme file
image

**Comment by joyyir** [comment]
> It looks like that you missed the readme file ![image](https://private-user-

fixed. thank you.

**Review by monkeyDluffy6017 — APPROVED** [review]

**Comment by joyyir** [comment]
@monkeyDluffy6017 Can you help us release a new version? I don't have an Apache LDAP account. So I can't publish to Maven Central Repository.

**Comment by monkeyDluffy6017** [comment]
@nic-chen Could you help this?

**Comment by joyyir** [comment]
@tzssangglass Can you support release new version?

**Pull request merged**
