### PR TITLE
fix: convert the conf req to an object and put it in the cache

### PR DESCRIPTION
**Pull request by tzssangglass**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
fix: https://github.com/apache/apisix-java-plugin-runner/issues/63
___
### Bugfix
- Description
Conf Req is currently put directly into the cache, but Conf Req is a DirectByteBuffer and multiple reads in different Http Call Reqs will cause exceptions
- How to fix?
Convert the conf req to an object and put it in the cache to avoid errors caused by reading the buffer multiple times.

___
### New feature or improvement
- Describe the details and related test reports.

- Source branch

- Related commits and pull requests

- Target branch

### CODE REVIEW

**Comment by tzssangglass** [comment]
relate to: https://github.com/apache/apisix-java-plugin-runner/issues/72

**Comment by tzssangglass** [comment]
@huang-x-h @Rdebu pls verify this PR if fix your problem.

**Review by spacewander — APPROVED** [review]

**Comment by huang-x-h** [comment]
There is no problem for the time being, continue to observe for a few days

> @huang-x-h @Rdebu pls verify this PR if fix your problem.

**Comment by tzssangglass** [comment]
@seominho77 @dongqisilent verify this PR if fix your problem.

**Pull request merged**
