### PR TITLE
chore: remove unnecessary dependencies and IP clean

### PR DESCRIPTION
**Pull request by dmsolr**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bugfix
- Description

- How to fix?

1. remove unnecessary dependencies
2. IP clean: to distinguish LICENSE and NOTICE for binary and source code distribution

___
### New feature or improvement
- Describe the details and related test reports.

- Source branch

- Related commits and pull requests

- Target branch

### CODE REVIEW

**Review by spacewander — DISMISSED** [review]

**Comment by spacewander** [comment]
Err... The CI is broken.

**Comment by dmsolr** [comment]
> Err... The CI is broken.

Yeap. Because I removed the `logback`, but there is a test case depend on it. @tzssangglass is going to fix it and submit it soon.

**Review by tzssangglass — APPROVED** [review]

**Comment by dmsolr** [comment]
@tzssangglass hi, I found some cases depend on Logging. I think logging is unstable. It is also because it depends on `logback`.

**Comment by tzssangglass** [comment]
> @tzssangglass hi, I found some cases depend on Logging. I think logging is unstable. It is also because it depends on `logback`.

got, fix later

**Review by tzssangglass — APPROVED** [review]

**Comment by tzssangglass** [comment]
@dmsolr is this PR ready？

**Review by spacewander — APPROVED** [review]

**Pull request merged**
