### PR TITLE
docs: remove "experimental" from the STATUS section

### PR DESCRIPTION
**Pull request by guoqqqi**
Please answer these questions before submitting a pull request

Update README:
Remove "experimental" from the STATUS section

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance

### CODE REVIEW

**Comment by guoqqqi** [comment]
Hi, @tzssangglass I just changed the contents of the README, but some of the E2E tests failed, can you help guide me to fix them?

**Comment by tzssangglass** [comment]
> Hi, @tzssangglass I just changed the contents of the README, but some of the E2E tests failed, can you help guide me to fix them?

rerun, if also failed I would fix latter

**Review by juzhiyuan — DISMISSED** [review]

**Comment by tzssangglass** [comment]
wait for https://github.com/apache/apisix-java-plugin-runner/pull/197 merged

**Comment by tzssangglass** [comment]
@guoqqqi pls merge the main branch of upstream to your PR

**Review by soulbird — APPROVED** [review]

**Pull request merged**
