### PR TITLE
bug: `ExtraInfoResponse` class `getResult` method bug

### PR DESCRIPTION
**Pull request by joyyir**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
#243 

___
### Bugfix
- Description
see #243 

- How to fix?
  - Instead of casting to `char`, cast to `byte`
  - `setBody` with byte array instead of `String`
  - `getBody` with `Charset`
___
### New feature or improvement
- Describe the details and related test reports.

- Source branch

- Related commits and pull requests

- Target branch

### CODE REVIEW

**Comment by nic-chen** [comment]
This is a breaking change, even though the original bug existed.

We should add new methods to solve this issue, and then remove the problematic methods in a later version, what do you think?

**Comment by joyyir** [comment]
> This is a breaking change, even though the original bug existed.
> 
> We should add new methods to solve this issue, and then remove the problematic methods in a later version, what do you think?

I agree. I'll try to write another version, so please review it later.

**Comment by joyyir** [comment]
Added a new method while maintaining the original method.

**Comment by nic-chen** [comment]
hi @joyyir  please fix the failed CI , thanks.

**Comment by joyyir** [comment]
> hi @joyyir please fix the failed CI , thanks.

Okay, I've added license header. Thanks.

**Review by Gallardot — APPROVED** [review]

**Pull request merged**
